// mockApplicants.js
const mockApplicants = [
    {
      applicationID: 1,
      applicationDate: "2024-06-15",
      userFirstname: "John",
      userLastname: "Doe",
      userEmail: "john.doe@example.com",
      userContactNum: "123-456-7890",
      userAge: 28,
      catcherID: 101,
      username: "john_doe",
      commissionTitle: "Errand 1",
      applicationStatus: "Pending",
    },
    {
      applicationID: 2,
      applicationDate: "2024-06-14",
      userFirstname: "Jane",
      userLastname: "Smith",
      userEmail: "jane.smith@example.com",
      userContactNum: "098-765-4321",
      userAge: 32,
      catcherID: 102,
      username: "jane_smith",
      commissionTitle: "Errand 2",
      applicationStatus: "Accepted",
    },
    {
        applicationID: 3,
        applicationDate: "2024-06-14",
        userFirstname: "Jane",
        userLastname: "Smith",
        userEmail: "jane.smith@example.com",
        userContactNum: "098-765-4321",
        userAge: 32,
        catcherID: 102,
        username: "jane_smith",
        commissionTitle: "Errand 2",
        applicationStatus: "Accepted",
      },
      {
        applicationID: 4,
        applicationDate: "2024-06-14",
        userFirstname: "Jane",
        userLastname: "Smith",
        userEmail: "jane.smith@example.com",
        userContactNum: "098-765-4321",
        userAge: 32,
        catcherID: 102,
        username: "jane_smith",
        commissionTitle: "Errand 2",
        applicationStatus: "Accepted",
      },
      {
        applicationID: 5,
        applicationDate: "2024-06-14",
        userFirstname: "Jane",
        userLastname: "Smith",
        userEmail: "jane.smith@example.com",
        userContactNum: "098-765-4321",
        userAge: 32,
        catcherID: 102,
        username: "jane_smith",
        commissionTitle: "Errand 2",
        applicationStatus: "Accepted",
      },
      {
        applicationID: 6,
        applicationDate: "2024-06-14",
        userFirstname: "Jane",
        userLastname: "Smith",
        userEmail: "jane.smith@example.com",
        userContactNum: "098-765-4321",
        userAge: 32,
        catcherID: 102,
        username: "jane_smith",
        commissionTitle: "Errand 2",
        applicationStatus: "Declined",
      },
      {
        applicationID: 7,
        applicationDate: "2024-06-14",
        userFirstname: "Jane",
        userLastname: "Smith",
        userEmail: "jane.smith@example.com",
        userContactNum: "098-765-4321",
        userAge: 32,
        catcherID: 102,
        username: "jane_smith",
        commissionTitle: "Errand 2",
        applicationStatus: "Accepted",
      },
  ];
  
  export default mockApplicants;
  